//
// Generated file github.com/nutanix/ntnx-api-golang-mock-pc/generated-code/protobuf/common/v1/response/response.proto.
//
// Product version: 1.0.0-SNAPSHOT
//
// Part of the GoLang Mock API - REST API for Mock Cat Service
//
// (c) 2025 Nutanix Inc.  All rights reserved
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: github.com/nutanix/ntnx-api-golang-mock-pc/generated-code/protobuf/common/v1/response/response.proto

package response

import (
	config "github.com/nutanix/ntnx-api-golang-mock-pc/generated-code/protobuf/common/v1/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A HATEOAS style link for the response.  Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource.
type ApiLink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL at which the entity described by the link can be accessed.
	Href *string `protobuf:"bytes,1001,opt,name=href" json:"href,omitempty"`
	// A name that identifies the relationship of the link to the object that is returned by the URL.  The unique value of \"self\" identifies the URL for the object.
	Rel           *string `protobuf:"bytes,1002,opt,name=rel" json:"rel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiLink) Reset() {
	*x = ApiLink{}
	mi := &file_common_v1_response_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiLink) ProtoMessage() {}

func (x *ApiLink) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_response_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiLink.ProtoReflect.Descriptor instead.
func (*ApiLink) Descriptor() ([]byte, []int) {
	return file_common_v1_response_response_proto_rawDescGZIP(), []int{0}
}

func (x *ApiLink) GetHref() string {
	if x != nil && x.Href != nil {
		return *x.Href
	}
	return ""
}

func (x *ApiLink) GetRel() string {
	if x != nil && x.Rel != nil {
		return *x.Rel
	}
	return ""
}

// Array wrapper message
type ApiLinkArrayWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         []*ApiLink `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiLinkArrayWrapper) Reset() {
	*x = ApiLinkArrayWrapper{}
	mi := &file_common_v1_response_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiLinkArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiLinkArrayWrapper) ProtoMessage() {}

func (x *ApiLinkArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_response_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiLinkArrayWrapper.ProtoReflect.Descriptor instead.
func (*ApiLinkArrayWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_response_response_proto_rawDescGZIP(), []int{1}
}

func (x *ApiLinkArrayWrapper) GetValue() []*ApiLink {
	if x != nil {
		return x.Value
	}
	return nil
}

// The metadata associated with an API response. This value is always present and minimally contains the self-link for the API request that produced this response. It also contains pagination data for the paginated requests.
type ApiResponseMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An array of flags that may indicate the status of the response. For example, a flag with the name 'isPaginated' and value 'false', indicates that the response is not paginated.
	Flags *config.FlagArrayWrapper `protobuf:"bytes,1001,opt,name=flags" json:"flags,omitempty"`
	// An array of HATEOAS style links for the response that may also include pagination links for list operations.
	Links *ApiLinkArrayWrapper `protobuf:"bytes,1002,opt,name=links" json:"links,omitempty"`
	// The total number of entities that are available on the server for this type.
	TotalAvailableResults *int32 `protobuf:"varint,1003,opt,name=total_available_results,json=totalAvailableResults" json:"total_available_results,omitempty"`
	// Information, Warning or Error messages that might provide additional contextual information related to the operation.
	Messages *config.MessageArrayWrapper `protobuf:"bytes,1004,opt,name=messages" json:"messages,omitempty"`
	// An array of entity-specific metadata
	ExtraInfo     *config.KVPairArrayWrapper `protobuf:"bytes,1005,opt,name=extra_info,json=extraInfo" json:"extra_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMetadata) Reset() {
	*x = ApiResponseMetadata{}
	mi := &file_common_v1_response_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMetadata) ProtoMessage() {}

func (x *ApiResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_response_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMetadata.ProtoReflect.Descriptor instead.
func (*ApiResponseMetadata) Descriptor() ([]byte, []int) {
	return file_common_v1_response_response_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseMetadata) GetFlags() *config.FlagArrayWrapper {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *ApiResponseMetadata) GetLinks() *ApiLinkArrayWrapper {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ApiResponseMetadata) GetTotalAvailableResults() int32 {
	if x != nil && x.TotalAvailableResults != nil {
		return *x.TotalAvailableResults
	}
	return 0
}

func (x *ApiResponseMetadata) GetMessages() *config.MessageArrayWrapper {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ApiResponseMetadata) GetExtraInfo() *config.KVPairArrayWrapper {
	if x != nil {
		return x.ExtraInfo
	}
	return nil
}

var File_common_v1_response_response_proto protoreflect.FileDescriptor

const file_common_v1_response_response_proto_rawDesc = "" +
	"\n" +
	"!github.com/nutanix/ntnx-api-golang-mock-pc/generated-code/protobuf/common/v1/response/response.proto\x12\x12common.v1.response\x1a\x1dgithub.com/nutanix/ntnx-api-golang-mock-pc/generated-code/protobuf/common/v1/config/config.proto\"1\n" +
	"\aApiLink\x12\x13\n" +
	"\x04href\x18\xe9\a \x01(\tR\x04href\x12\x11\n" +
	"\x03rel\x18\xea\a \x01(\tR\x03rel\"I\n" +
	"\x13ApiLinkArrayWrapper\x122\n" +
	"\x05value\x18\xe8\a \x03(\v2\x1b.common.v1.response.ApiLinkR\x05value\"\xd3\x02\n" +
	"\x13ApiResponseMetadata\x129\n" +
	"\x05flags\x18\xe9\a \x01(\v2\".common.v1.config.FlagArrayWrapperR\x05flags\x12>\n" +
	"\x05links\x18\xea\a \x01(\v2'.common.v1.response.ApiLinkArrayWrapperR\x05links\x127\n" +
	"\x17total_available_results\x18\xeb\a \x01(\x05R\x15totalAvailableResults\x12B\n" +
	"\bmessages\x18\xec\a \x01(\v2%.common.v1.config.MessageArrayWrapperR\bmessages\x12D\n" +
	"\n" +
	"extra_info\x18\xed\a \x01(\v2$.common.v1.config.KVPairArrayWrapperR\textraInfoB*\n" +
	"\x12common.v1.responseP\x01Z\x12github.com/nutanix/ntnx-api-golang-mock-pc/generated-code/protobuf/common/v1/response"

var (
	file_common_v1_response_response_proto_rawDescOnce sync.Once
	file_common_v1_response_response_proto_rawDescData []byte
)

func file_common_v1_response_response_proto_rawDescGZIP() []byte {
	file_common_v1_response_response_proto_rawDescOnce.Do(func() {
		file_common_v1_response_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_response_response_proto_rawDesc), len(file_common_v1_response_response_proto_rawDesc)))
	})
	return file_common_v1_response_response_proto_rawDescData
}

var file_common_v1_response_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_v1_response_response_proto_goTypes = []any{
	(*ApiLink)(nil),                    // 0: common.v1.response.ApiLink
	(*ApiLinkArrayWrapper)(nil),        // 1: common.v1.response.ApiLinkArrayWrapper
	(*ApiResponseMetadata)(nil),        // 2: common.v1.response.ApiResponseMetadata
	(*config.FlagArrayWrapper)(nil),    // 3: common.v1.config.FlagArrayWrapper
	(*config.MessageArrayWrapper)(nil), // 4: common.v1.config.MessageArrayWrapper
	(*config.KVPairArrayWrapper)(nil),  // 5: common.v1.config.KVPairArrayWrapper
}
var file_common_v1_response_response_proto_depIdxs = []int32{
	0, // 0: common.v1.response.ApiLinkArrayWrapper.value:type_name -> common.v1.response.ApiLink
	3, // 1: common.v1.response.ApiResponseMetadata.flags:type_name -> common.v1.config.FlagArrayWrapper
	1, // 2: common.v1.response.ApiResponseMetadata.links:type_name -> common.v1.response.ApiLinkArrayWrapper
	4, // 3: common.v1.response.ApiResponseMetadata.messages:type_name -> common.v1.config.MessageArrayWrapper
	5, // 4: common.v1.response.ApiResponseMetadata.extra_info:type_name -> common.v1.config.KVPairArrayWrapper
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_v1_response_response_proto_init() }
func file_common_v1_response_response_proto_init() {
	if File_common_v1_response_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_response_response_proto_rawDesc), len(file_common_v1_response_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_response_response_proto_goTypes,
		DependencyIndexes: file_common_v1_response_response_proto_depIdxs,
		MessageInfos:      file_common_v1_response_response_proto_msgTypes,
	}.Build()
	File_common_v1_response_response_proto = out.File
	file_common_v1_response_response_proto_goTypes = nil
	file_common_v1_response_response_proto_depIdxs = nil
}
