//
// Generated file common/v1/config/config.proto.
//
// Product version: 16.8.0-SNAPSHOT
//
// Part of the AZ-Manager - The new GoLang grpc service to achieve new layer of abstraction of PCs.
//
// (c) 2025 Nutanix Inc.  All rights reserved
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: common/v1/config/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageSeverityMessage_MessageSeverity int32

const (
	MessageSeverityMessage_UNKNOWN  MessageSeverityMessage_MessageSeverity = 0
	MessageSeverityMessage_REDACTED MessageSeverityMessage_MessageSeverity = 1
	MessageSeverityMessage_INFO     MessageSeverityMessage_MessageSeverity = 1001
	MessageSeverityMessage_WARNING  MessageSeverityMessage_MessageSeverity = 1002
	MessageSeverityMessage_ERROR    MessageSeverityMessage_MessageSeverity = 1003
)

// Enum value maps for MessageSeverityMessage_MessageSeverity.
var (
	MessageSeverityMessage_MessageSeverity_name = map[int32]string{
		0:    "UNKNOWN",
		1:    "REDACTED",
		1001: "INFO",
		1002: "WARNING",
		1003: "ERROR",
	}
	MessageSeverityMessage_MessageSeverity_value = map[string]int32{
		"UNKNOWN":  0,
		"REDACTED": 1,
		"INFO":     1001,
		"WARNING":  1002,
		"ERROR":    1003,
	}
)

func (x MessageSeverityMessage_MessageSeverity) Enum() *MessageSeverityMessage_MessageSeverity {
	p := new(MessageSeverityMessage_MessageSeverity)
	*p = x
	return p
}

func (x MessageSeverityMessage_MessageSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageSeverityMessage_MessageSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_config_config_proto_enumTypes[0].Descriptor()
}

func (MessageSeverityMessage_MessageSeverity) Type() protoreflect.EnumType {
	return &file_common_v1_config_config_proto_enumTypes[0]
}

func (x MessageSeverityMessage_MessageSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MessageSeverityMessage_MessageSeverity) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MessageSeverityMessage_MessageSeverity(num)
	return nil
}

// Deprecated: Use MessageSeverityMessage_MessageSeverity.Descriptor instead.
func (MessageSeverityMessage_MessageSeverity) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{19, 0}
}

// Array wrapper message
type IPAddressOrFQDNArrayWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         []*IPAddressOrFQDN `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddressOrFQDNArrayWrapper) Reset() {
	*x = IPAddressOrFQDNArrayWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddressOrFQDNArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddressOrFQDNArrayWrapper) ProtoMessage() {}

func (x *IPAddressOrFQDNArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddressOrFQDNArrayWrapper.ProtoReflect.Descriptor instead.
func (*IPAddressOrFQDNArrayWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *IPAddressOrFQDNArrayWrapper) GetValue() []*IPAddressOrFQDN {
	if x != nil {
		return x.Value
	}
	return nil
}

// An authentication scheme that requires the client to present a username and password. The server will service the request only if it can validate the user-ID and password for the protection space of the Request-URI.
type BasicAuth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username required for the basic auth scheme. As per [RFC 2617](https://datatracker.ietf.org/doc/html/rfc2617) usernames might be case sensitive.
	Username *string `protobuf:"bytes,2001,opt,name=username" json:"username,omitempty"`
	// Password required for the basic auth scheme.
	Password      *string `protobuf:"bytes,2002,opt,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicAuth) Reset() {
	*x = BasicAuth{}
	mi := &file_common_v1_config_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuth) ProtoMessage() {}

func (x *BasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuth.ProtoReflect.Descriptor instead.
func (*BasicAuth) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *BasicAuth) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *BasicAuth) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

// A fully qualified domain name that specifies its exact location in the tree hierarchy of the Domain Name System.
type FQDN struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fully qualified domain name of the host.
	Value         *string `protobuf:"bytes,1001,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FQDN) Reset() {
	*x = FQDN{}
	mi := &file_common_v1_config_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FQDN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FQDN) ProtoMessage() {}

func (x *FQDN) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FQDN.ProtoReflect.Descriptor instead.
func (*FQDN) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{2}
}

func (x *FQDN) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// Many entities in the Nutanix APIs carry flags.  This object captures all the flags associated with that entity through this object.  The field that hosts this type of object must have an attribute called x-bounded-map-keys that tells which flags are actually present for that entity.
type Flag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the flag.
	Name *string `protobuf:"bytes,1001,opt,name=name" json:"name,omitempty"`
	// Value of the flag.
	Value         *bool `protobuf:"varint,1002,opt,name=value,def=0" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Flag fields.
const (
	Default_Flag_Value = bool(false)
)

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_common_v1_config_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{3}
}

func (x *Flag) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Flag) GetValue() bool {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return Default_Flag_Value
}

// An unique address that identifies a device on the internet or a local network in IPv4 or IPv6 format.
type IPAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ipv4 *IPv4Address `protobuf:"bytes,1001,opt,name=ipv4" json:"ipv4,omitempty"`
	Ipv6          *IPv6Address `protobuf:"bytes,1002,opt,name=ipv6" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddress) Reset() {
	*x = IPAddress{}
	mi := &file_common_v1_config_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddress) ProtoMessage() {}

func (x *IPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddress.ProtoReflect.Descriptor instead.
func (*IPAddress) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{4}
}

func (x *IPAddress) GetIpv4() *IPv4Address {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *IPAddress) GetIpv6() *IPv6Address {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

// An unique address that identifies a device on the internet or a local network in IPv4/IPv6 format or a Fully Qualified Domain Name.
type IPAddressOrFQDN struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ipv4 *IPv4Address `protobuf:"bytes,1001,opt,name=ipv4" json:"ipv4,omitempty"`
	Ipv6 *IPv6Address `protobuf:"bytes,1002,opt,name=ipv6" json:"ipv6,omitempty"`
	Fqdn          *FQDN `protobuf:"bytes,1003,opt,name=fqdn" json:"fqdn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddressOrFQDN) Reset() {
	*x = IPAddressOrFQDN{}
	mi := &file_common_v1_config_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddressOrFQDN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddressOrFQDN) ProtoMessage() {}

func (x *IPAddressOrFQDN) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddressOrFQDN.ProtoReflect.Descriptor instead.
func (*IPAddressOrFQDN) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{5}
}

func (x *IPAddressOrFQDN) GetIpv4() *IPv4Address {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *IPAddressOrFQDN) GetIpv6() *IPv6Address {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

func (x *IPAddressOrFQDN) GetFqdn() *FQDN {
	if x != nil {
		return x.Fqdn
	}
	return nil
}

// An unique address that identifies a device on the internet or a local network in IPv4 format.
type IPv4Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IPv4 address of the host.
	Value *string `protobuf:"bytes,1001,opt,name=value" json:"value,omitempty"`
	// The prefix length of the network to which this host IPv4 address belongs.
	PrefixLength  *int32 `protobuf:"varint,1002,opt,name=prefix_length,json=prefixLength,def=32" json:"prefix_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for IPv4Address fields.
const (
	Default_IPv4Address_PrefixLength = int32(32)
)

func (x *IPv4Address) Reset() {
	*x = IPv4Address{}
	mi := &file_common_v1_config_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPv4Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv4Address) ProtoMessage() {}

func (x *IPv4Address) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv4Address.ProtoReflect.Descriptor instead.
func (*IPv4Address) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{6}
}

func (x *IPv4Address) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *IPv4Address) GetPrefixLength() int32 {
	if x != nil && x.PrefixLength != nil {
		return *x.PrefixLength
	}
	return Default_IPv4Address_PrefixLength
}

// An unique address that identifies a device on the internet or a local network in IPv6 format.
type IPv6Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IPv6 address of the host.
	Value *string `protobuf:"bytes,1001,opt,name=value" json:"value,omitempty"`
	// The prefix length of the network to which this host IPv6 address belongs.
	PrefixLength  *int32 `protobuf:"varint,1002,opt,name=prefix_length,json=prefixLength,def=128" json:"prefix_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for IPv6Address fields.
const (
	Default_IPv6Address_PrefixLength = int32(128)
)

func (x *IPv6Address) Reset() {
	*x = IPv6Address{}
	mi := &file_common_v1_config_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPv6Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv6Address) ProtoMessage() {}

func (x *IPv6Address) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv6Address.ProtoReflect.Descriptor instead.
func (*IPv6Address) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{7}
}

func (x *IPv6Address) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *IPv6Address) GetPrefixLength() int32 {
	if x != nil && x.PrefixLength != nil {
		return *x.PrefixLength
	}
	return Default_IPv6Address_PrefixLength
}

// Range of consecutive IP addresses that can be assigned to a specific Subnet.The size of the IP range is determined by the subnet mask.
type IpRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Begin *IPAddress `protobuf:"bytes,1001,opt,name=begin" json:"begin,omitempty"`
	End           *IPAddress `protobuf:"bytes,1002,opt,name=end" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpRange) Reset() {
	*x = IpRange{}
	mi := &file_common_v1_config_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpRange) ProtoMessage() {}

func (x *IpRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpRange.ProtoReflect.Descriptor instead.
func (*IpRange) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{8}
}

func (x *IpRange) GetBegin() *IPAddress {
	if x != nil {
		return x.Begin
	}
	return nil
}

func (x *IpRange) GetEnd() *IPAddress {
	if x != nil {
		return x.End
	}
	return nil
}

// OneOf item wrapper message
type StringWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in oneOf item wrapper message
	Value         *string `protobuf:"bytes,1000,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringWrapper) Reset() {
	*x = StringWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringWrapper) ProtoMessage() {}

func (x *StringWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringWrapper.ProtoReflect.Descriptor instead.
func (*StringWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{9}
}

func (x *StringWrapper) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// OneOf item wrapper message
type IntegerWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in oneOf item wrapper message
	Value         *int32 `protobuf:"varint,1000,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegerWrapper) Reset() {
	*x = IntegerWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegerWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegerWrapper) ProtoMessage() {}

func (x *IntegerWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegerWrapper.ProtoReflect.Descriptor instead.
func (*IntegerWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{10}
}

func (x *IntegerWrapper) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

// OneOf item wrapper message
type BooleanWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in oneOf item wrapper message
	Value         *bool `protobuf:"varint,1000,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanWrapper) Reset() {
	*x = BooleanWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanWrapper) ProtoMessage() {}

func (x *BooleanWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanWrapper.ProtoReflect.Descriptor instead.
func (*BooleanWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{11}
}

func (x *BooleanWrapper) GetValue() bool {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return false
}

// OneOf item wrapper message
type StringArrayWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in oneOf item wrapper message
	Value         []string `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringArrayWrapper) Reset() {
	*x = StringArrayWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArrayWrapper) ProtoMessage() {}

func (x *StringArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArrayWrapper.ProtoReflect.Descriptor instead.
func (*StringArrayWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{12}
}

func (x *StringArrayWrapper) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

// Map wrapper message
type StringMapWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         map[string]string `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMapWrapper) Reset() {
	*x = StringMapWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMapWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMapWrapper) ProtoMessage() {}

func (x *StringMapWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMapWrapper.ProtoReflect.Descriptor instead.
func (*StringMapWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{13}
}

func (x *StringMapWrapper) GetValue() map[string]string {
	if x != nil {
		return x.Value
	}
	return nil
}

// OneOf item wrapper message
type MapOfStringWrapperArrayWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in oneOf item wrapper message
	Value         []*MapOfStringWrapper `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapOfStringWrapperArrayWrapper) Reset() {
	*x = MapOfStringWrapperArrayWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapOfStringWrapperArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapOfStringWrapperArrayWrapper) ProtoMessage() {}

func (x *MapOfStringWrapperArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapOfStringWrapperArrayWrapper.ProtoReflect.Descriptor instead.
func (*MapOfStringWrapperArrayWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{14}
}

func (x *MapOfStringWrapperArrayWrapper) GetValue() []*MapOfStringWrapper {
	if x != nil {
		return x.Value
	}
	return nil
}

// OneOf item wrapper message
type IntegerArrayWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in oneOf item wrapper message
	Value         []int32 `protobuf:"varint,1000,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegerArrayWrapper) Reset() {
	*x = IntegerArrayWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegerArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegerArrayWrapper) ProtoMessage() {}

func (x *IntegerArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegerArrayWrapper.ProtoReflect.Descriptor instead.
func (*IntegerArrayWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{15}
}

func (x *IntegerArrayWrapper) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

// A map describing a set of keys and their corresponding values.
type KVPair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A map describing a set of keys and their corresponding values.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*KVPair_StringValue
	//	*KVPair_IntegerValue
	//	*KVPair_BooleanValue
	//	*KVPair_StringArrayValue
	//	*KVPair_StringMapValue
	//	*KVPair_MapOfStringWrapperArrayValue
	//	*KVPair_IntegerArrayValue
	Value isKVPair_Value `protobuf_oneof:"value"`
	// The key of the key-value pair.
	Name          *string `protobuf:"bytes,1001,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPair) Reset() {
	*x = KVPair{}
	mi := &file_common_v1_config_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPair) ProtoMessage() {}

func (x *KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPair.ProtoReflect.Descriptor instead.
func (*KVPair) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{16}
}

func (x *KVPair) GetValue() isKVPair_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KVPair) GetStringValue() *StringWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_StringValue); ok {
			return x.StringValue
		}
	}
	return nil
}

func (x *KVPair) GetIntegerValue() *IntegerWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_IntegerValue); ok {
			return x.IntegerValue
		}
	}
	return nil
}

func (x *KVPair) GetBooleanValue() *BooleanWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return nil
}

func (x *KVPair) GetStringArrayValue() *StringArrayWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_StringArrayValue); ok {
			return x.StringArrayValue
		}
	}
	return nil
}

func (x *KVPair) GetStringMapValue() *StringMapWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_StringMapValue); ok {
			return x.StringMapValue
		}
	}
	return nil
}

func (x *KVPair) GetMapOfStringWrapperArrayValue() *MapOfStringWrapperArrayWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_MapOfStringWrapperArrayValue); ok {
			return x.MapOfStringWrapperArrayValue
		}
	}
	return nil
}

func (x *KVPair) GetIntegerArrayValue() *IntegerArrayWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_IntegerArrayValue); ok {
			return x.IntegerArrayValue
		}
	}
	return nil
}

func (x *KVPair) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type isKVPair_Value interface {
	isKVPair_Value()
}

type KVPair_StringValue struct {
	// A string value in a key-value pair.
	StringValue *StringWrapper `protobuf:"bytes,1002,opt,name=string_value,json=stringValue,oneof"`
}

type KVPair_IntegerValue struct {
	// An integer value in a key-value pair.
	IntegerValue *IntegerWrapper `protobuf:"bytes,1003,opt,name=integer_value,json=integerValue,oneof"`
}

type KVPair_BooleanValue struct {
	// An boolean value in a key-value pair.
	BooleanValue *BooleanWrapper `protobuf:"bytes,1004,opt,name=boolean_value,json=booleanValue,oneof"`
}

type KVPair_StringArrayValue struct {
	// A value in a key-value pair that represents a list of strings.
	StringArrayValue *StringArrayWrapper `protobuf:"bytes,1005,opt,name=string_array_value,json=stringArrayValue,oneof"`
}

type KVPair_StringMapValue struct {
	// A value in a key-value pair that represents a map of string keys and values.
	StringMapValue *StringMapWrapper `protobuf:"bytes,1006,opt,name=string_map_value,json=stringMapValue,oneof"`
}

type KVPair_MapOfStringWrapperArrayValue struct {
	// A value in a key-value pair that represents an array of maps of string keys and values.
	MapOfStringWrapperArrayValue *MapOfStringWrapperArrayWrapper `protobuf:"bytes,1007,opt,name=map_of_string_wrapper_array_value,json=mapOfStringWrapperArrayValue,oneof"`
}

type KVPair_IntegerArrayValue struct {
	// A value in a key-value pair that represents a list of integers.
	IntegerArrayValue *IntegerArrayWrapper `protobuf:"bytes,1008,opt,name=integer_array_value,json=integerArrayValue,oneof"`
}

func (*KVPair_StringValue) isKVPair_Value() {}

func (*KVPair_IntegerValue) isKVPair_Value() {}

func (*KVPair_BooleanValue) isKVPair_Value() {}

func (*KVPair_StringArrayValue) isKVPair_Value() {}

func (*KVPair_StringMapValue) isKVPair_Value() {}

func (*KVPair_MapOfStringWrapperArrayValue) isKVPair_Value() {}

func (*KVPair_IntegerArrayValue) isKVPair_Value() {}

// A wrapper schema containing a map with string keys and values.
type MapOfStringWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A map with string keys and values.
	Map           *StringMapWrapper `protobuf:"bytes,1001,opt,name=map" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapOfStringWrapper) Reset() {
	*x = MapOfStringWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapOfStringWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapOfStringWrapper) ProtoMessage() {}

func (x *MapOfStringWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapOfStringWrapper.ProtoReflect.Descriptor instead.
func (*MapOfStringWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{17}
}

func (x *MapOfStringWrapper) GetMap() *StringMapWrapper {
	if x != nil {
		return x.Map
	}
	return nil
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A code that uniquely identifies a message.
	Code *string `protobuf:"bytes,1001,opt,name=code" json:"code,omitempty"`
	// The description of the message.
	Message *string `protobuf:"bytes,1002,opt,name=message" json:"message,omitempty"`
	// The locale for the message description.
	Locale *string `protobuf:"bytes,1003,opt,name=locale,def=en_US" json:"locale,omitempty"`
	Severity      *MessageSeverityMessage_MessageSeverity `protobuf:"varint,1004,opt,name=severity,enum=common.v1.config.MessageSeverityMessage_MessageSeverity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Message fields.
const (
	Default_Message_Locale = string("en_US")
)

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_common_v1_config_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{18}
}

func (x *Message) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *Message) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *Message) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return Default_Message_Locale
}

func (x *Message) GetSeverity() MessageSeverityMessage_MessageSeverity {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return MessageSeverityMessage_UNKNOWN
}

// The message severity.
type MessageSeverityMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSeverityMessage) Reset() {
	*x = MessageSeverityMessage{}
	mi := &file_common_v1_config_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSeverityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSeverityMessage) ProtoMessage() {}

func (x *MessageSeverityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSeverityMessage.ProtoReflect.Descriptor instead.
func (*MessageSeverityMessage) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{19}
}

// Map wrapper message
type ObjectMapWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         map[string]*anypb.Any `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMapWrapper) Reset() {
	*x = ObjectMapWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMapWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMapWrapper) ProtoMessage() {}

func (x *ObjectMapWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMapWrapper.ProtoReflect.Descriptor instead.
func (*ObjectMapWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{20}
}

func (x *ObjectMapWrapper) GetValue() map[string]*anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

// A model base class whose instances are bound to a specific tenant.  This model adds a tenantId to the base model class that it extends and is automatically set by the server.
type TenantAwareModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A globally unique identifier that represents the tenant that owns this entity. The system automatically assigns it, and it and is immutable from an API consumer perspective (some use cases may cause this ID to change - For instance, a use case may require the transfer of ownership of the entity, but these cases are handled automatically on the server).
	TenantId *string `protobuf:"bytes,1001,opt,name=tenant_id,json=tenantId" json:"tenant_id,omitempty"`
	XReserved     *ObjectMapWrapper `protobuf:"bytes,900000,opt,name=_reserved,json=Reserved" json:"_reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantAwareModel) Reset() {
	*x = TenantAwareModel{}
	mi := &file_common_v1_config_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantAwareModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantAwareModel) ProtoMessage() {}

func (x *TenantAwareModel) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantAwareModel.ProtoReflect.Descriptor instead.
func (*TenantAwareModel) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{21}
}

func (x *TenantAwareModel) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *TenantAwareModel) GetXReserved() *ObjectMapWrapper {
	if x != nil {
		return x.XReserved
	}
	return nil
}

// Array wrapper message
type FlagArrayWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         []*Flag `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagArrayWrapper) Reset() {
	*x = FlagArrayWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagArrayWrapper) ProtoMessage() {}

func (x *FlagArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagArrayWrapper.ProtoReflect.Descriptor instead.
func (*FlagArrayWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{22}
}

func (x *FlagArrayWrapper) GetValue() []*Flag {
	if x != nil {
		return x.Value
	}
	return nil
}

// Array wrapper message
type MessageArrayWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         []*Message `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageArrayWrapper) Reset() {
	*x = MessageArrayWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageArrayWrapper) ProtoMessage() {}

func (x *MessageArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageArrayWrapper.ProtoReflect.Descriptor instead.
func (*MessageArrayWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{23}
}

func (x *MessageArrayWrapper) GetValue() []*Message {
	if x != nil {
		return x.Value
	}
	return nil
}

// Array wrapper message
type KVPairArrayWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         []*KVPair `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPairArrayWrapper) Reset() {
	*x = KVPairArrayWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPairArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPairArrayWrapper) ProtoMessage() {}

func (x *KVPairArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPairArrayWrapper.ProtoReflect.Descriptor instead.
func (*KVPairArrayWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{24}
}

func (x *KVPairArrayWrapper) GetValue() []*KVPair {
	if x != nil {
		return x.Value
	}
	return nil
}

// Array wrapper message
type IpRangeArrayWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         []*IpRange `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpRangeArrayWrapper) Reset() {
	*x = IpRangeArrayWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpRangeArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpRangeArrayWrapper) ProtoMessage() {}

func (x *IpRangeArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpRangeArrayWrapper.ProtoReflect.Descriptor instead.
func (*IpRangeArrayWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{25}
}

func (x *IpRangeArrayWrapper) GetValue() []*IpRange {
	if x != nil {
		return x.Value
	}
	return nil
}

// Array wrapper message
type IPAddressArrayWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         []*IPAddress `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddressArrayWrapper) Reset() {
	*x = IPAddressArrayWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddressArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddressArrayWrapper) ProtoMessage() {}

func (x *IPAddressArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddressArrayWrapper.ProtoReflect.Descriptor instead.
func (*IPAddressArrayWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{26}
}

func (x *IPAddressArrayWrapper) GetValue() []*IPAddress {
	if x != nil {
		return x.Value
	}
	return nil
}

// Array wrapper message
type BasicAuthArrayWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         []*BasicAuth `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicAuthArrayWrapper) Reset() {
	*x = BasicAuthArrayWrapper{}
	mi := &file_common_v1_config_config_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicAuthArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuthArrayWrapper) ProtoMessage() {}

func (x *BasicAuthArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_config_config_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuthArrayWrapper.ProtoReflect.Descriptor instead.
func (*BasicAuthArrayWrapper) Descriptor() ([]byte, []int) {
	return file_common_v1_config_config_proto_rawDescGZIP(), []int{27}
}

func (x *BasicAuthArrayWrapper) GetValue() []*BasicAuth {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_common_v1_config_config_proto protoreflect.FileDescriptor

const file_common_v1_config_config_proto_rawDesc = "" +
	"\n" +
	"\x1dcommon/v1/config/config.proto\x12\x10common.v1.config\x1a\x19google/protobuf/any.proto\"W\n" +
	"\x1bIPAddressOrFQDNArrayWrapper\x128\n" +
	"\x05value\x18\xe8\a \x03(\v2!.common.v1.config.IPAddressOrFQDNR\x05value\"E\n" +
	"\tBasicAuth\x12\x1b\n" +
	"\busername\x18\xd1\x0f \x01(\tR\busername\x12\x1b\n" +
	"\bpassword\x18\xd2\x0f \x01(\tR\bpassword\"\x1d\n" +
	"\x04FQDN\x12\x15\n" +
	"\x05value\x18\xe9\a \x01(\tR\x05value\"9\n" +
	"\x04Flag\x12\x13\n" +
	"\x04name\x18\xe9\a \x01(\tR\x04name\x12\x1c\n" +
	"\x05value\x18\xea\a \x01(\b:\x05falseR\x05value\"s\n" +
	"\tIPAddress\x122\n" +
	"\x04ipv4\x18\xe9\a \x01(\v2\x1d.common.v1.config.IPv4AddressR\x04ipv4\x122\n" +
	"\x04ipv6\x18\xea\a \x01(\v2\x1d.common.v1.config.IPv6AddressR\x04ipv6\"\xa6\x01\n" +
	"\x0fIPAddressOrFQDN\x122\n" +
	"\x04ipv4\x18\xe9\a \x01(\v2\x1d.common.v1.config.IPv4AddressR\x04ipv4\x122\n" +
	"\x04ipv6\x18\xea\a \x01(\v2\x1d.common.v1.config.IPv6AddressR\x04ipv6\x12+\n" +
	"\x04fqdn\x18\xeb\a \x01(\v2\x16.common.v1.config.FQDNR\x04fqdn\"N\n" +
	"\vIPv4Address\x12\x15\n" +
	"\x05value\x18\xe9\a \x01(\tR\x05value\x12(\n" +
	"\rprefix_length\x18\xea\a \x01(\x05:\x0232R\fprefixLength\"O\n" +
	"\vIPv6Address\x12\x15\n" +
	"\x05value\x18\xe9\a \x01(\tR\x05value\x12)\n" +
	"\rprefix_length\x18\xea\a \x01(\x05:\x03128R\fprefixLength\"m\n" +
	"\aIpRange\x122\n" +
	"\x05begin\x18\xe9\a \x01(\v2\x1b.common.v1.config.IPAddressR\x05begin\x12.\n" +
	"\x03end\x18\xea\a \x01(\v2\x1b.common.v1.config.IPAddressR\x03end\"&\n" +
	"\rStringWrapper\x12\x15\n" +
	"\x05value\x18\xe8\a \x01(\tR\x05value\"'\n" +
	"\x0eIntegerWrapper\x12\x15\n" +
	"\x05value\x18\xe8\a \x01(\x05R\x05value\"'\n" +
	"\x0eBooleanWrapper\x12\x15\n" +
	"\x05value\x18\xe8\a \x01(\bR\x05value\"+\n" +
	"\x12StringArrayWrapper\x12\x15\n" +
	"\x05value\x18\xe8\a \x03(\tR\x05value\"\x92\x01\n" +
	"\x10StringMapWrapper\x12D\n" +
	"\x05value\x18\xe8\a \x03(\v2-.common.v1.config.StringMapWrapper.ValueEntryR\x05value\x1a8\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x1eMapOfStringWrapperArrayWrapper\x12;\n" +
	"\x05value\x18\xe8\a \x03(\v2$.common.v1.config.MapOfStringWrapperR\x05value\",\n" +
	"\x13IntegerArrayWrapper\x12\x15\n" +
	"\x05value\x18\xe8\a \x03(\x05R\x05value\"\x81\x05\n" +
	"\x06KVPair\x12E\n" +
	"\fstring_value\x18\xea\a \x01(\v2\x1f.common.v1.config.StringWrapperH\x00R\vstringValue\x12H\n" +
	"\rinteger_value\x18\xeb\a \x01(\v2 .common.v1.config.IntegerWrapperH\x00R\fintegerValue\x12H\n" +
	"\rboolean_value\x18\xec\a \x01(\v2 .common.v1.config.BooleanWrapperH\x00R\fbooleanValue\x12U\n" +
	"\x12string_array_value\x18\xed\a \x01(\v2$.common.v1.config.StringArrayWrapperH\x00R\x10stringArrayValue\x12O\n" +
	"\x10string_map_value\x18\xee\a \x01(\v2\".common.v1.config.StringMapWrapperH\x00R\x0estringMapValue\x12|\n" +
	"!map_of_string_wrapper_array_value\x18\xef\a \x01(\v20.common.v1.config.MapOfStringWrapperArrayWrapperH\x00R\x1cmapOfStringWrapperArrayValue\x12X\n" +
	"\x13integer_array_value\x18\xf0\a \x01(\v2%.common.v1.config.IntegerArrayWrapperH\x00R\x11integerArrayValue\x12\x13\n" +
	"\x04name\x18\xe9\a \x01(\tR\x04nameB\a\n" +
	"\x05value\"K\n" +
	"\x12MapOfStringWrapper\x125\n" +
	"\x03map\x18\xe9\a \x01(\v2\".common.v1.config.StringMapWrapperR\x03map\"\xb0\x01\n" +
	"\aMessage\x12\x13\n" +
	"\x04code\x18\xe9\a \x01(\tR\x04code\x12\x19\n" +
	"\amessage\x18\xea\a \x01(\tR\amessage\x12\x1e\n" +
	"\x06locale\x18\xeb\a \x01(\t:\x05en_USR\x06locale\x12U\n" +
	"\bseverity\x18\xec\a \x01(\x0e28.common.v1.config.MessageSeverityMessage.MessageSeverityR\bseverity\"k\n" +
	"\x16MessageSeverityMessage\"Q\n" +
	"\x0fMessageSeverity\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bREDACTED\x10\x01\x12\t\n" +
	"\x04INFO\x10\xe9\a\x12\f\n" +
	"\aWARNING\x10\xea\a\x12\n" +
	"\n" +
	"\x05ERROR\x10\xeb\a\"\xa8\x01\n" +
	"\x10ObjectMapWrapper\x12D\n" +
	"\x05value\x18\xe8\a \x03(\v2-.common.v1.config.ObjectMapWrapper.ValueEntryR\x05value\x1aN\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"s\n" +
	"\x10TenantAwareModel\x12\x1c\n" +
	"\ttenant_id\x18\xe9\a \x01(\tR\btenantId\x12A\n" +
	"\t_reserved\x18\xa0\xf76 \x01(\v2\".common.v1.config.ObjectMapWrapperR\bReserved\"A\n" +
	"\x10FlagArrayWrapper\x12-\n" +
	"\x05value\x18\xe8\a \x03(\v2\x16.common.v1.config.FlagR\x05value\"G\n" +
	"\x13MessageArrayWrapper\x120\n" +
	"\x05value\x18\xe8\a \x03(\v2\x19.common.v1.config.MessageR\x05value\"E\n" +
	"\x12KVPairArrayWrapper\x12/\n" +
	"\x05value\x18\xe8\a \x03(\v2\x18.common.v1.config.KVPairR\x05value\"G\n" +
	"\x13IpRangeArrayWrapper\x120\n" +
	"\x05value\x18\xe8\a \x03(\v2\x19.common.v1.config.IpRangeR\x05value\"K\n" +
	"\x15IPAddressArrayWrapper\x122\n" +
	"\x05value\x18\xe8\a \x03(\v2\x1b.common.v1.config.IPAddressR\x05value\"K\n" +
	"\x15BasicAuthArrayWrapper\x122\n" +
	"\x05value\x18\xe8\a \x03(\v2\x1b.common.v1.config.BasicAuthR\x05valueB&\n" +
	"\x10common.v1.configP\x01Z\x10common/v1/config"

var (
	file_common_v1_config_config_proto_rawDescOnce sync.Once
	file_common_v1_config_config_proto_rawDescData []byte
)

func file_common_v1_config_config_proto_rawDescGZIP() []byte {
	file_common_v1_config_config_proto_rawDescOnce.Do(func() {
		file_common_v1_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_config_config_proto_rawDesc), len(file_common_v1_config_config_proto_rawDesc)))
	})
	return file_common_v1_config_config_proto_rawDescData
}

var file_common_v1_config_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_common_v1_config_config_proto_goTypes = []any{
	(MessageSeverityMessage_MessageSeverity)(0), // 0: common.v1.config.MessageSeverityMessage.MessageSeverity
	(*IPAddressOrFQDNArrayWrapper)(nil),         // 1: common.v1.config.IPAddressOrFQDNArrayWrapper
	(*BasicAuth)(nil),                           // 2: common.v1.config.BasicAuth
	(*FQDN)(nil),                                // 3: common.v1.config.FQDN
	(*Flag)(nil),                                // 4: common.v1.config.Flag
	(*IPAddress)(nil),                           // 5: common.v1.config.IPAddress
	(*IPAddressOrFQDN)(nil),                     // 6: common.v1.config.IPAddressOrFQDN
	(*IPv4Address)(nil),                         // 7: common.v1.config.IPv4Address
	(*IPv6Address)(nil),                         // 8: common.v1.config.IPv6Address
	(*IpRange)(nil),                             // 9: common.v1.config.IpRange
	(*StringWrapper)(nil),                       // 10: common.v1.config.StringWrapper
	(*IntegerWrapper)(nil),                      // 11: common.v1.config.IntegerWrapper
	(*BooleanWrapper)(nil),                      // 12: common.v1.config.BooleanWrapper
	(*StringArrayWrapper)(nil),                  // 13: common.v1.config.StringArrayWrapper
	(*StringMapWrapper)(nil),                    // 14: common.v1.config.StringMapWrapper
	(*MapOfStringWrapperArrayWrapper)(nil),      // 15: common.v1.config.MapOfStringWrapperArrayWrapper
	(*IntegerArrayWrapper)(nil),                 // 16: common.v1.config.IntegerArrayWrapper
	(*KVPair)(nil),                              // 17: common.v1.config.KVPair
	(*MapOfStringWrapper)(nil),                  // 18: common.v1.config.MapOfStringWrapper
	(*Message)(nil),                             // 19: common.v1.config.Message
	(*MessageSeverityMessage)(nil),              // 20: common.v1.config.MessageSeverityMessage
	(*ObjectMapWrapper)(nil),                    // 21: common.v1.config.ObjectMapWrapper
	(*TenantAwareModel)(nil),                    // 22: common.v1.config.TenantAwareModel
	(*FlagArrayWrapper)(nil),                    // 23: common.v1.config.FlagArrayWrapper
	(*MessageArrayWrapper)(nil),                 // 24: common.v1.config.MessageArrayWrapper
	(*KVPairArrayWrapper)(nil),                  // 25: common.v1.config.KVPairArrayWrapper
	(*IpRangeArrayWrapper)(nil),                 // 26: common.v1.config.IpRangeArrayWrapper
	(*IPAddressArrayWrapper)(nil),               // 27: common.v1.config.IPAddressArrayWrapper
	(*BasicAuthArrayWrapper)(nil),               // 28: common.v1.config.BasicAuthArrayWrapper
	nil,                                         // 29: common.v1.config.StringMapWrapper.ValueEntry
	nil,                                         // 30: common.v1.config.ObjectMapWrapper.ValueEntry
	(*anypb.Any)(nil),                           // 31: google.protobuf.Any
}
var file_common_v1_config_config_proto_depIdxs = []int32{
	6,  // 0: common.v1.config.IPAddressOrFQDNArrayWrapper.value:type_name -> common.v1.config.IPAddressOrFQDN
	7,  // 1: common.v1.config.IPAddress.ipv4:type_name -> common.v1.config.IPv4Address
	8,  // 2: common.v1.config.IPAddress.ipv6:type_name -> common.v1.config.IPv6Address
	7,  // 3: common.v1.config.IPAddressOrFQDN.ipv4:type_name -> common.v1.config.IPv4Address
	8,  // 4: common.v1.config.IPAddressOrFQDN.ipv6:type_name -> common.v1.config.IPv6Address
	3,  // 5: common.v1.config.IPAddressOrFQDN.fqdn:type_name -> common.v1.config.FQDN
	5,  // 6: common.v1.config.IpRange.begin:type_name -> common.v1.config.IPAddress
	5,  // 7: common.v1.config.IpRange.end:type_name -> common.v1.config.IPAddress
	29, // 8: common.v1.config.StringMapWrapper.value:type_name -> common.v1.config.StringMapWrapper.ValueEntry
	18, // 9: common.v1.config.MapOfStringWrapperArrayWrapper.value:type_name -> common.v1.config.MapOfStringWrapper
	10, // 10: common.v1.config.KVPair.string_value:type_name -> common.v1.config.StringWrapper
	11, // 11: common.v1.config.KVPair.integer_value:type_name -> common.v1.config.IntegerWrapper
	12, // 12: common.v1.config.KVPair.boolean_value:type_name -> common.v1.config.BooleanWrapper
	13, // 13: common.v1.config.KVPair.string_array_value:type_name -> common.v1.config.StringArrayWrapper
	14, // 14: common.v1.config.KVPair.string_map_value:type_name -> common.v1.config.StringMapWrapper
	15, // 15: common.v1.config.KVPair.map_of_string_wrapper_array_value:type_name -> common.v1.config.MapOfStringWrapperArrayWrapper
	16, // 16: common.v1.config.KVPair.integer_array_value:type_name -> common.v1.config.IntegerArrayWrapper
	14, // 17: common.v1.config.MapOfStringWrapper.map:type_name -> common.v1.config.StringMapWrapper
	0,  // 18: common.v1.config.Message.severity:type_name -> common.v1.config.MessageSeverityMessage.MessageSeverity
	30, // 19: common.v1.config.ObjectMapWrapper.value:type_name -> common.v1.config.ObjectMapWrapper.ValueEntry
	21, // 20: common.v1.config.TenantAwareModel._reserved:type_name -> common.v1.config.ObjectMapWrapper
	4,  // 21: common.v1.config.FlagArrayWrapper.value:type_name -> common.v1.config.Flag
	19, // 22: common.v1.config.MessageArrayWrapper.value:type_name -> common.v1.config.Message
	17, // 23: common.v1.config.KVPairArrayWrapper.value:type_name -> common.v1.config.KVPair
	9,  // 24: common.v1.config.IpRangeArrayWrapper.value:type_name -> common.v1.config.IpRange
	5,  // 25: common.v1.config.IPAddressArrayWrapper.value:type_name -> common.v1.config.IPAddress
	2,  // 26: common.v1.config.BasicAuthArrayWrapper.value:type_name -> common.v1.config.BasicAuth
	31, // 27: common.v1.config.ObjectMapWrapper.ValueEntry.value:type_name -> google.protobuf.Any
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_common_v1_config_config_proto_init() }
func file_common_v1_config_config_proto_init() {
	if File_common_v1_config_config_proto != nil {
		return
	}
	file_common_v1_config_config_proto_msgTypes[16].OneofWrappers = []any{
		(*KVPair_StringValue)(nil),
		(*KVPair_IntegerValue)(nil),
		(*KVPair_BooleanValue)(nil),
		(*KVPair_StringArrayValue)(nil),
		(*KVPair_StringMapValue)(nil),
		(*KVPair_MapOfStringWrapperArrayValue)(nil),
		(*KVPair_IntegerArrayValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_config_config_proto_rawDesc), len(file_common_v1_config_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_config_config_proto_goTypes,
		DependencyIndexes: file_common_v1_config_config_proto_depIdxs,
		EnumInfos:         file_common_v1_config_config_proto_enumTypes,
		MessageInfos:      file_common_v1_config_config_proto_msgTypes,
	}.Build()
	File_common_v1_config_config_proto = out.File
	file_common_v1_config_config_proto_goTypes = nil
	file_common_v1_config_config_proto_depIdxs = nil
}
