//
// Generated file nexus/v4/config.proto.
//
// Product version: 1.0.0-SNAPSHOT
//
// Part of the GoLang Mock API - REST API for Mock Item Service
//
// (c) 2026 Nutanix Inc.  All rights reserved
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: nexus/v4/config/File_service.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"

	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadFileArg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ExtId         *string `protobuf:"bytes,2001,opt,name=ext_id,json=extId" json:"ext_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileArg) Reset() {
	*x = DownloadFileArg{}
	mi := &file_nexus_v4_config_File_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileArg) ProtoMessage() {}

func (x *DownloadFileArg) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v4_config_File_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileArg.ProtoReflect.Descriptor instead.
func (*DownloadFileArg) Descriptor() ([]byte, []int) {
	return file_nexus_v4_config_File_service_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadFileArg) GetExtId() string {
	if x != nil && x.ExtId != nil {
		return *x.ExtId
	}
	return ""
}

type DownloadFileRet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRet) Reset() {
	*x = DownloadFileRet{}
	mi := &file_nexus_v4_config_File_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRet) ProtoMessage() {}

func (x *DownloadFileRet) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v4_config_File_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRet.ProtoReflect.Descriptor instead.
func (*DownloadFileRet) Descriptor() ([]byte, []int) {
	return file_nexus_v4_config_File_service_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadFileRet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// message containing all attributes expected in the uploadFile request
type UploadFileArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileArg) Reset() {
	*x = UploadFileArg{}
	mi := &file_nexus_v4_config_File_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileArg) ProtoMessage() {}

func (x *UploadFileArg) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v4_config_File_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileArg.ProtoReflect.Descriptor instead.
func (*UploadFileArg) Descriptor() ([]byte, []int) {
	return file_nexus_v4_config_File_service_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileArg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// message containing all attributes expected in the uploadFile response
type UploadFileRet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// field containing expected response content
	Content *File `protobuf:"bytes,999,opt,name=content" json:"content,omitempty"`
	// map containing headers expected in response
	Reserved      map[string]string `protobuf:"bytes,1000,rep,name=reserved" json:"reserved,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRet) Reset() {
	*x = UploadFileRet{}
	mi := &file_nexus_v4_config_File_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRet) ProtoMessage() {}

func (x *UploadFileRet) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v4_config_File_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRet.ProtoReflect.Descriptor instead.
func (*UploadFileRet) Descriptor() ([]byte, []int) {
	return file_nexus_v4_config_File_service_proto_rawDescGZIP(), []int{3}
}

func (x *UploadFileRet) GetContent() *File {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadFileRet) GetReserved() map[string]string {
	if x != nil {
		return x.Reserved
	}
	return nil
}

var File_nexus_v4_config_File_service_proto protoreflect.FileDescriptor

const file_nexus_v4_config_File_service_proto_rawDesc = "" +
	"\n" +
	"\"nexus/v4/config/File_service.proto\x12\x0fnexus.v4.config\x1a\x1anexus/v4/api_version.proto\x1a\"nexus/v4/http_method_options.proto\x1a\x1cnexus/v4/config/config.proto\x1a\x19google/protobuf/any.proto\")\n" +
	"\x0fDownloadFileArg\x12\x16\n" +
	"\x06ext_id\x18\xd1\x0f \x01(\tR\x05extId\"%\n" +
	"\x0fDownloadFileRet\x12\x12\n" +
	"\x04data\x18\x01 \x02(\fR\x04data\"#\n" +
	"\rUploadFileArg\x12\x12\n" +
	"\x04data\x18\x01 \x02(\fR\x04data\"\xc9\x01\n" +
	"\rUploadFileRet\x120\n" +
	"\acontent\x18\xe7\a \x01(\v2\x15.nexus.v4.config.FileR\acontent\x12I\n" +
	"\breserved\x18\xe8\a \x03(\v2,.nexus.v4.config.UploadFileRet.ReservedEntryR\breserved\x1a;\n" +
	"\rReservedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x84\x02\n" +
	"\vFileService\x12|\n" +
	"\fdownloadFile\x12 .nexus.v4.config.DownloadFileArg\x1a .nexus.v4.config.DownloadFileRet\"&\xc2>#*!/nexus/v4/config/download/{extId}0\x01\x12l\n" +
	"\n" +
	"uploadFile\x12\x1e.nexus.v4.config.UploadFileArg\x1a\x1e.nexus.v4.config.UploadFileRet\"\x1c\xc2>\x19\n" +
	"\x17/nexus/v4/config/upload(\x01\x1a\t\x82}\x06\n" +
	"\x014\x12\x011B$\n" +
	"\x0fnexus.v4.configP\x01Z\x0fnexus/v4/config"

var (
	file_nexus_v4_config_File_service_proto_rawDescOnce sync.Once
	file_nexus_v4_config_File_service_proto_rawDescData []byte
)

func file_nexus_v4_config_File_service_proto_rawDescGZIP() []byte {
	file_nexus_v4_config_File_service_proto_rawDescOnce.Do(func() {
		file_nexus_v4_config_File_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_v4_config_File_service_proto_rawDesc), len(file_nexus_v4_config_File_service_proto_rawDesc)))
	})
	return file_nexus_v4_config_File_service_proto_rawDescData
}

var file_nexus_v4_config_File_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_nexus_v4_config_File_service_proto_goTypes = []any{
	(*DownloadFileArg)(nil), // 0: nexus.v4.config.DownloadFileArg
	(*DownloadFileRet)(nil), // 1: nexus.v4.config.DownloadFileRet
	(*UploadFileArg)(nil),   // 2: nexus.v4.config.UploadFileArg
	(*UploadFileRet)(nil),   // 3: nexus.v4.config.UploadFileRet
	nil,                     // 4: nexus.v4.config.UploadFileRet.ReservedEntry
	(*File)(nil),            // 5: nexus.v4.config.File
}
var file_nexus_v4_config_File_service_proto_depIdxs = []int32{
	5, // 0: nexus.v4.config.UploadFileRet.content:type_name -> nexus.v4.config.File
	4, // 1: nexus.v4.config.UploadFileRet.reserved:type_name -> nexus.v4.config.UploadFileRet.ReservedEntry
	0, // 2: nexus.v4.config.FileService.downloadFile:input_type -> nexus.v4.config.DownloadFileArg
	2, // 3: nexus.v4.config.FileService.uploadFile:input_type -> nexus.v4.config.UploadFileArg
	1, // 4: nexus.v4.config.FileService.downloadFile:output_type -> nexus.v4.config.DownloadFileRet
	3, // 5: nexus.v4.config.FileService.uploadFile:output_type -> nexus.v4.config.UploadFileRet
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nexus_v4_config_File_service_proto_init() }
func file_nexus_v4_config_File_service_proto_init() {
	if File_nexus_v4_config_File_service_proto != nil {
		return
	}
	file_nexus_v4_config_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_v4_config_File_service_proto_rawDesc), len(file_nexus_v4_config_File_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_v4_config_File_service_proto_goTypes,
		DependencyIndexes: file_nexus_v4_config_File_service_proto_depIdxs,
		MessageInfos:      file_nexus_v4_config_File_service_proto_msgTypes,
	}.Build()
	File_nexus_v4_config_File_service_proto = out.File
	file_nexus_v4_config_File_service_proto_goTypes = nil
	file_nexus_v4_config_File_service_proto_depIdxs = nil
}
