//
// Generated file nexus/v4/stats.proto.
//
// Product version: 1.0.0-SNAPSHOT
//
// Part of the GoLang Mock API - REST API for Mock Item Service
//
// (c) 2026 Nutanix Inc.  All rights reserved
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: nexus/v4/stats/ItemStats_service.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListItemStatsArg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A URL query parameter that allows clients to filter a collection of resources. The expression specified with $filter is evaluated for each resource in the collection, and only items where the expression evaluates to true are included in the response. Expression specified with the $filter must conform to the [OData V4.01](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html) URL conventions.
	// For example, filter **$filter=name eq 'karbon-ntnx-1.0'** would filter the result on cluster name 'karbon-ntnx1.0', filter **$filter=startswith(name, 'C')** would filter on cluster name starting with 'C'.
	XFilter *string `protobuf:"bytes,101,opt,name=_filter,json=Filter" json:"_filter,omitempty"`
	// A URL query parameter that allows clients to specify the sort criteria for the returned list of objects. Resources can be sorted in ascending order using asc or descending order using desc. If asc or desc are not specified, the resources will be sorted in ascending order by default. For example, '$orderby=templateName desc' would get all templates sorted by templateName in descending order.
	XOrderby *string `protobuf:"bytes,102,opt,name=_orderby,json=Orderby" json:"_orderby,omitempty"`
	// A URL query parameter that allows clients to specify a sequence of transformations to the entity set, such as groupby, filter, aggregate etc. As of now only support for groupby exists.For example '$apply=groupby((templateName))' would get all templates grouped by templateName.
	XApply        *string `protobuf:"bytes,104,opt,name=_apply,json=Apply" json:"_apply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemStatsArg) Reset() {
	*x = ListItemStatsArg{}
	mi := &file_nexus_v4_stats_ItemStats_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemStatsArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemStatsArg) ProtoMessage() {}

func (x *ListItemStatsArg) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v4_stats_ItemStats_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemStatsArg.ProtoReflect.Descriptor instead.
func (*ListItemStatsArg) Descriptor() ([]byte, []int) {
	return file_nexus_v4_stats_ItemStats_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListItemStatsArg) GetXFilter() string {
	if x != nil && x.XFilter != nil {
		return *x.XFilter
	}
	return ""
}

func (x *ListItemStatsArg) GetXOrderby() string {
	if x != nil && x.XOrderby != nil {
		return *x.XOrderby
	}
	return ""
}

func (x *ListItemStatsArg) GetXApply() string {
	if x != nil && x.XApply != nil {
		return *x.XApply
	}
	return ""
}

// message containing all attributes expected in the listItemStats response
type ListItemStatsRet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// field containing expected response content
	Content *ListItemStatsApiResponse `protobuf:"bytes,999,opt,name=content" json:"content,omitempty"`
	// map containing headers expected in response
	Reserved      map[string]string `protobuf:"bytes,1000,rep,name=reserved" json:"reserved,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemStatsRet) Reset() {
	*x = ListItemStatsRet{}
	mi := &file_nexus_v4_stats_ItemStats_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemStatsRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemStatsRet) ProtoMessage() {}

func (x *ListItemStatsRet) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v4_stats_ItemStats_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemStatsRet.ProtoReflect.Descriptor instead.
func (*ListItemStatsRet) Descriptor() ([]byte, []int) {
	return file_nexus_v4_stats_ItemStats_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListItemStatsRet) GetContent() *ListItemStatsApiResponse {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ListItemStatsRet) GetReserved() map[string]string {
	if x != nil {
		return x.Reserved
	}
	return nil
}

var File_nexus_v4_stats_ItemStats_service_proto protoreflect.FileDescriptor

const file_nexus_v4_stats_ItemStats_service_proto_rawDesc = "" +
	"\n" +
	"&nexus/v4/stats/ItemStats_service.proto\x12\x0enexus.v4.stats\x1a\x1anexus/v4/api_version.proto\x1a\"nexus/v4/http_method_options.proto\x1a\x1anexus/v4/stats/stats.proto\"]\n" +
	"\x10ListItemStatsArg\x12\x17\n" +
	"\a_filter\x18e \x01(\tR\x06Filter\x12\x19\n" +
	"\b_orderby\x18f \x01(\tR\aOrderby\x12\x15\n" +
	"\x06_apply\x18h \x01(\tR\x05Apply\"\xe1\x01\n" +
	"\x10ListItemStatsRet\x12C\n" +
	"\acontent\x18\xe7\a \x01(\v2(.nexus.v4.stats.ListItemStatsApiResponseR\acontent\x12K\n" +
	"\breserved\x18\xe8\a \x03(\v2..nexus.v4.stats.ListItemStatsRet.ReservedEntryR\breserved\x1a;\n" +
	"\rReservedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x93\x01\n" +
	"\x10ItemStatsService\x12t\n" +
	"\rlistItemStats\x12 .nexus.v4.stats.ListItemStatsArg\x1a .nexus.v4.stats.ListItemStatsRet\"\x1f\xc2>\x1c*\x1a/nexus/v4/stats/item-stats\x1a\t\x82}\x06\n" +
	"\x014\x12\x011B\"\n" +
	"\x0enexus.v4.statsP\x01Z\x0enexus/v4/stats"

var (
	file_nexus_v4_stats_ItemStats_service_proto_rawDescOnce sync.Once
	file_nexus_v4_stats_ItemStats_service_proto_rawDescData []byte
)

func file_nexus_v4_stats_ItemStats_service_proto_rawDescGZIP() []byte {
	file_nexus_v4_stats_ItemStats_service_proto_rawDescOnce.Do(func() {
		file_nexus_v4_stats_ItemStats_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_v4_stats_ItemStats_service_proto_rawDesc), len(file_nexus_v4_stats_ItemStats_service_proto_rawDesc)))
	})
	return file_nexus_v4_stats_ItemStats_service_proto_rawDescData
}

var file_nexus_v4_stats_ItemStats_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nexus_v4_stats_ItemStats_service_proto_goTypes = []any{
	(*ListItemStatsArg)(nil),         // 0: nexus.v4.stats.ListItemStatsArg
	(*ListItemStatsRet)(nil),         // 1: nexus.v4.stats.ListItemStatsRet
	nil,                              // 2: nexus.v4.stats.ListItemStatsRet.ReservedEntry
	(*ListItemStatsApiResponse)(nil), // 3: nexus.v4.stats.ListItemStatsApiResponse
}
var file_nexus_v4_stats_ItemStats_service_proto_depIdxs = []int32{
	3, // 0: nexus.v4.stats.ListItemStatsRet.content:type_name -> nexus.v4.stats.ListItemStatsApiResponse
	2, // 1: nexus.v4.stats.ListItemStatsRet.reserved:type_name -> nexus.v4.stats.ListItemStatsRet.ReservedEntry
	0, // 2: nexus.v4.stats.ItemStatsService.listItemStats:input_type -> nexus.v4.stats.ListItemStatsArg
	1, // 3: nexus.v4.stats.ItemStatsService.listItemStats:output_type -> nexus.v4.stats.ListItemStatsRet
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nexus_v4_stats_ItemStats_service_proto_init() }
func file_nexus_v4_stats_ItemStats_service_proto_init() {
	if File_nexus_v4_stats_ItemStats_service_proto != nil {
		return
	}
	file_nexus_v4_stats_stats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_v4_stats_ItemStats_service_proto_rawDesc), len(file_nexus_v4_stats_ItemStats_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_v4_stats_ItemStats_service_proto_goTypes,
		DependencyIndexes: file_nexus_v4_stats_ItemStats_service_proto_depIdxs,
		MessageInfos:      file_nexus_v4_stats_ItemStats_service_proto_msgTypes,
	}.Build()
	File_nexus_v4_stats_ItemStats_service_proto = out.File
	file_nexus_v4_stats_ItemStats_service_proto_goTypes = nil
	file_nexus_v4_stats_ItemStats_service_proto_depIdxs = nil
}
