// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mock/v4/http_method_options.proto

package v4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpMethodOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	POST          *string                `protobuf:"bytes,1,opt,name=POST" json:"POST,omitempty"`
	PATCH         *string                `protobuf:"bytes,2,opt,name=PATCH" json:"PATCH,omitempty"`
	PUT           *string                `protobuf:"bytes,3,opt,name=PUT" json:"PUT,omitempty"`
	DELETE        *string                `protobuf:"bytes,4,opt,name=DELETE" json:"DELETE,omitempty"`
	GET           *string                `protobuf:"bytes,5,opt,name=GET" json:"GET,omitempty"`
	HEAD          *string                `protobuf:"bytes,6,opt,name=HEAD" json:"HEAD,omitempty"`
	OPTIONS       *string                `protobuf:"bytes,7,opt,name=OPTIONS" json:"OPTIONS,omitempty"`
	TRACE         *string                `protobuf:"bytes,8,opt,name=TRACE" json:"TRACE,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpMethodOptions) Reset() {
	*x = HttpMethodOptions{}
	mi := &file_mock_v4_http_method_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpMethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpMethodOptions) ProtoMessage() {}

func (x *HttpMethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mock_v4_http_method_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpMethodOptions.ProtoReflect.Descriptor instead.
func (*HttpMethodOptions) Descriptor() ([]byte, []int) {
	return file_mock_v4_http_method_options_proto_rawDescGZIP(), []int{0}
}

func (x *HttpMethodOptions) GetPOST() string {
	if x != nil && x.POST != nil {
		return *x.POST
	}
	return ""
}

func (x *HttpMethodOptions) GetPATCH() string {
	if x != nil && x.PATCH != nil {
		return *x.PATCH
	}
	return ""
}

func (x *HttpMethodOptions) GetPUT() string {
	if x != nil && x.PUT != nil {
		return *x.PUT
	}
	return ""
}

func (x *HttpMethodOptions) GetDELETE() string {
	if x != nil && x.DELETE != nil {
		return *x.DELETE
	}
	return ""
}

func (x *HttpMethodOptions) GetGET() string {
	if x != nil && x.GET != nil {
		return *x.GET
	}
	return ""
}

func (x *HttpMethodOptions) GetHEAD() string {
	if x != nil && x.HEAD != nil {
		return *x.HEAD
	}
	return ""
}

func (x *HttpMethodOptions) GetOPTIONS() string {
	if x != nil && x.OPTIONS != nil {
		return *x.OPTIONS
	}
	return ""
}

func (x *HttpMethodOptions) GetTRACE() string {
	if x != nil && x.TRACE != nil {
		return *x.TRACE
	}
	return ""
}

var file_mock_v4_http_method_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpMethodOptions)(nil),
		Field:         1000,
		Name:          "mock.v4.ntnx_api_http",
		Tag:           "bytes,1000,opt,name=ntnx_api_http",
		Filename:      "github.com/nutanix/ntnx-api-golang-mock-pc/generated-code/protobuf/mock/v4/http_method_options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional mock.v4.HttpMethodOptions ntnx_api_http = 1000;
	E_NtnxApiHttp = &file_mock_v4_http_method_options_proto_extTypes[0]
)

var File_mock_v4_http_method_options_proto protoreflect.FileDescriptor

const file_mock_v4_http_method_options_proto_rawDesc = "" +
	"\n" +
	"!mock/v4/http_method_options.proto\x12\amock.v4\x1a google/protobuf/descriptor.proto\"\xbd\x01\n" +
	"\x11HttpMethodOptions\x12\x12\n" +
	"\x04POST\x18\x01 \x01(\tR\x04POST\x12\x14\n" +
	"\x05PATCH\x18\x02 \x01(\tR\x05PATCH\x12\x10\n" +
	"\x03PUT\x18\x03 \x01(\tR\x03PUT\x12\x16\n" +
	"\x06DELETE\x18\x04 \x01(\tR\x06DELETE\x12\x10\n" +
	"\x03GET\x18\x05 \x01(\tR\x03GET\x12\x12\n" +
	"\x04HEAD\x18\x06 \x01(\tR\x04HEAD\x12\x18\n" +
	"\aOPTIONS\x18\a \x01(\tR\aOPTIONS\x12\x14\n" +
	"\x05TRACE\x18\b \x01(\tR\x05TRACE:_\n" +
	"\rntnx_api_http\x12\x1e.google.protobuf.MethodOptions\x18\xe8\a \x01(\v2\x1a.mock.v4.HttpMethodOptionsR\vntnxApiHttpB\x14\n" +
	"\amock.v4P\x01Z\amock/v4"

var (
	file_mock_v4_http_method_options_proto_rawDescOnce sync.Once
	file_mock_v4_http_method_options_proto_rawDescData []byte
)

func file_mock_v4_http_method_options_proto_rawDescGZIP() []byte {
	file_mock_v4_http_method_options_proto_rawDescOnce.Do(func() {
		file_mock_v4_http_method_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mock_v4_http_method_options_proto_rawDesc), len(file_mock_v4_http_method_options_proto_rawDesc)))
	})
	return file_mock_v4_http_method_options_proto_rawDescData
}

var file_mock_v4_http_method_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mock_v4_http_method_options_proto_goTypes = []any{
	(*HttpMethodOptions)(nil),          // 0: mock.v4.HttpMethodOptions
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_mock_v4_http_method_options_proto_depIdxs = []int32{
	1, // 0: mock.v4.ntnx_api_http:extendee -> google.protobuf.MethodOptions
	0, // 1: mock.v4.ntnx_api_http:type_name -> mock.v4.HttpMethodOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mock_v4_http_method_options_proto_init() }
func file_mock_v4_http_method_options_proto_init() {
	if File_mock_v4_http_method_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mock_v4_http_method_options_proto_rawDesc), len(file_mock_v4_http_method_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_mock_v4_http_method_options_proto_goTypes,
		DependencyIndexes: file_mock_v4_http_method_options_proto_depIdxs,
		MessageInfos:      file_mock_v4_http_method_options_proto_msgTypes,
		ExtensionInfos:    file_mock_v4_http_method_options_proto_extTypes,
	}.Build()
	File_mock_v4_http_method_options_proto = out.File
	file_mock_v4_http_method_options_proto_goTypes = nil
	file_mock_v4_http_method_options_proto_depIdxs = nil
}
